// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/about.tsx";
import * as $4 from "./routes/api/joke.ts";
import * as $5 from "./routes/blog/[slug].tsx";
import * as $6 from "./routes/blog/index.tsx";
import * as $7 from "./routes/contact.tsx";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/portfolio/[...slug].tsx";
import * as $10 from "./routes/portfolio/index.tsx";
import * as $11 from "./routes/privacy.tsx";
import * as $12 from "./routes/snippets/[slug].tsx";
import * as $13 from "./routes/snippets/index.tsx";
import * as $14 from "./routes/types/Project.ts";
import * as $$0 from "./islands/Disqus.tsx";
import * as $$1 from "./islands/ImagesView.tsx";
import * as $$2 from "./islands/ListProjects.tsx";
import * as $$3 from "./islands/ListTags.tsx";
import * as $$4 from "./islands/Markdown.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/about.tsx": $3,
    "./routes/api/joke.ts": $4,
    "./routes/blog/[slug].tsx": $5,
    "./routes/blog/index.tsx": $6,
    "./routes/contact.tsx": $7,
    "./routes/index.tsx": $8,
    "./routes/portfolio/[...slug].tsx": $9,
    "./routes/portfolio/index.tsx": $10,
    "./routes/privacy.tsx": $11,
    "./routes/snippets/[slug].tsx": $12,
    "./routes/snippets/index.tsx": $13,
    "./routes/types/Project.ts": $14,
  },
  islands: {
    "./islands/Disqus.tsx": $$0,
    "./islands/ImagesView.tsx": $$1,
    "./islands/ListProjects.tsx": $$2,
    "./islands/ListTags.tsx": $$3,
    "./islands/Markdown.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
